#!/bin/bash
#Script to CD to my private dropbox and open vim with the file name

cd ~/Dropbox/Ubuntu/scripts;
if [ -z "$1" ];
then	
	echo "Error: You did not specify a file name\n";
else
	#check if file exists as a script!!! I will add a sepearte bash script for editing bash scripts
	if hash $1 2>/dev/null; then
		echo "It exists already!"
	else
		echo "#!/bin/bash" >> ~/Dropbox/Ubuntu/scripts/$1
		vim $1;
		echo "Are you sure you want to create this script? Enter Y for yes"
		read user_input
		if [ "$user_input" == "Y" ];
		then
			chmod 755 ~/Dropbox/Ubuntu/scripts/$1;
			echo "Created Bash Script $1\n"
		else
			echo "Do you want to delete this script? Y for yes"
			read user_input
			if [ "$user_input" == "Y" ]; then
				echo "Deleting Script"
				rm ~/Dropbox/Ubuntu/scripts/$1
			else
				echo "Exiting, but keeping script"
			fi
		fi
	fi
fi
